### ISSUE TITLE
SerialProber filter issue

### ISSUE THREAD

**Issue by agendek78** [mozilla-iot/zigbee-adapter#102]
When filtering by productID and vendorID and them contains letters matching fails on some systems. For instance CC2531 dongle productID on ubuntu is '16a8' and on windows is '16A8'. So comparison should not be case sensitive.

**Comment by dhylands** [comment]
Good point - thanks for the report.

**Comment by dhylands** [comment]
It turns out serial prober allows regular expressions to be used for the filter. I updated the serial-test.js to use regular expressions rather than just a string. https://github.com/mozilla-iot/serial-prober-node/pull/3

You can replace `'16a8' ` with `/16a8/i` and it will do a case insensitive comparison. I'll also update the zigbee adapter to use this to make it more obvious that a regular expression can be used.

**Comment by agendek78** [comment]
ok
