### ISSUE TITLE
ikea TRÅDFRI Wireless motion sensor

### ISSUE THREAD

**Issue by vincentserpoul** [mozilla-iot/zigbee-adapter#160]
item: https://www.ikea.com/us/en/p/tradfri-wireless-motion-sensor-white-50383505/

considering the price and the functionality, it would be nice to make it work properly.
I had quite some trouble to pair it, but I finally managed to.

Is there any walkthrough to help debug this?

(I created two separate issues for the 2 different hardware, not sure if it is the best idea)

**Comment by dhylands** [comment]
This sensor might work with the ConBee (or ConBee II) dongle, but it won't work with the Digi dongle.

The IKEA sensors assume that they're directly controlling a light, and the ConBee emulates a fake light. You'd need to turn on frame debugging to see exactly what messages the motion sensor sends to the "light" and then write handlers for it.

**Comment by vincentserpoul** [comment]
> This sensor might work with the ConBee (or ConBee II) dongle, but it won't work with the Digi dongle.

What makes it different?

I tried to add debug (rawFrames...) but nothing appears whatever I do, is it because I use the digi dongle or am I not doing the right thing to debug?

**Comment by dhylands** [comment]
The motion sensor will only talk directly to light bulbs and doesn't support talking thru a hub. The ConBee dongles added a feature where in addition to providing the coordinator functionality, they also emulate being a light bulb. This allows the ikea motion sensor to control the emulated light bulb and thus the conbee can determine when the motion sensor is detecting motion (since it sent commands to control the emulated light bulb).

The Digi dongle doesn't offer this emulation, so there is no way for it to tell when the motion sensor is detecting motion.

You probably don't want to debug rawFrames (which just prints the raw hex values of the frames), rather enable frames and frameDetail which will show the decoded frames. Having said that, it won't help in this scenario since the Digi dongle doesn't implement the emulatedlight bulb.

**Comment by vincentserpoul** [comment]
clear explanation, thank you!

**Comment by flatsiedatsie** [comment]
The Conbee 2 dongle seems to pick this up, and it's working fine here.

![tradfri_socket](https://user-images.githubusercontent.com/805405/73876893-0f587a00-4858-11ea-93d0-59257a71629c.png)

**Comment by johanroelofsen** [comment]
> The Conbee 2 dongle seems to pick this up, and it's working fine here.
Could you explain how you got the motion-sensor to pair? I have a Conbee 2 as well, tried factory resetting the sensor, holding pair button >10s. Maybe I am missing something? Thanks

**Comment by mrstegeman** [comment]
All models of the motion sensor should be working now.
