### ISSUE TITLE
Aqara Temperature sensor stops reporting after a while

### ISSUE THREAD

**Issue by PeterFour** [mozilla-iot/zigbee-adapter#203]
I recently bought the Aqara sensor WSDCGQ11LM I managed to pair it with no issue or at least that what I thought, but now it looks like the sensor no longer report anything after a while.

Looking at the frame it reported for an hour or so and then nothing for 8h+.

I'm using a DigiStick2 if that could be the issue. But right now the only solution I found to make it work again, is hard reset (sometime more than on time) before pairing again.

**Comment by mrstegeman** [comment]
The problem is that most of the older Aqara devices are not Zigbee compliant. They may or may not work better with a Conbee dongle.

@kgiori I know you have quite a few of these devices, any tips?

**Comment by PeterFour** [comment]
Ah that's what I feared after reading a bit about those things. To add to my comment it appears that now I can't even make it work at all. So if that's an issue I might try to return it and find another sensor

**Comment by kgiori** [comment]
I have a Xiaomi temperature sensor, not Aqara, even though they look rather similar. After pairing mine, it's been online for months. I have it paired with a Conbee II Zigbee dongle from Dresden Elektronik.

But why bother getting only temp when you can get more than temp for the same price? My favorite way to track temperature all over my house is to use Samsung SmartThings battery operated devices (highly reliable), since all of them include temperature:
* "multipurpose" sensor (door/window sensor)
* leak detector
* motion sensor
* pushbutton

**Comment by PeterFour** [comment]
@kgiori thanks for sharing, I'll keep my existing one and retest if I ever buy a Conbee II and funny you should say that, I just ended up ordering a Multipurpose sensor from Samsung today :D They do look very nice indeed, especially the fact they couple with the door sensor. That's a nice way to put a temp sensor without having to add a dedicated one for that. However I didn't see any pushbutton from them an I feel like I'll probably need one but I'll investigate
